---
version: '3.4'

services:
  grafana:
    image: grafana/grafana:8.5.3
    container_name: grafana
    # https://grafana.com/docs/grafana/latest/administration/configuration/#configure-with-environment-variables
    # https://grafana.com/docs/grafana/latest/auth/ldap/
    environment:
      - GF_SECURITY_ADMIN_USER={{ GRAFANA_ADMIN_USER }}
      - GF_SECURITY_ADMIN_PASSWORD={{ GRAFANA_ADMIN_PASSWORD }}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_AUTH_LDAP_ENABLED=true
      - GF_AUTH_LDAP_CONFIG_FILE=/etc/grafana/ldap.toml
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning/
    volumes:
      - /opt/grafana/ldap.toml:/etc/grafana/ldap.toml
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    labels:
      org.label-schema.group: "monitoring"

volumes:
  grafana_data:

